do_test: print summary to stderr

diff --git a/do_test b/do_test
--- a/do_test
+++ b/do_test
@@ -36,10 +36,10 @@ _on_exit() {
             (( TEST_RESULTS[i] == 0 && failed++ ))
         done
         if (( failed )); then
-            echo " *** ${failed} test(s) failed ***"
+            echo >&2 " *** ${failed} test(s) failed ***"
             exit 1
         else
-            echo " *** everything is OK ***"
+            echo >&2 " *** everything is OK ***"
             exit 0
         fi
     else
