do_test: fix a typo

diff --git a/do_test b/do_test
--- a/do_test
+++ b/do_test
@@ -43,7 +43,7 @@ _on_exit() {
             exit 0
         fi
     else
-        echo >&2 " *** fatal error occured ***"
+        echo >&2 " *** fatal error occurred ***"
         exit 1
     fi
 }
